name: Land
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  test:
    uses: NucleoidAI/actions/.github/workflows/test.yml@main
    secrets: inherit

  deploy:
    needs: test
    uses: NucleoidAI/actions/.github/workflows/deploy.yml@main
    secrets: inherit
