name: Land
on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  deploy:
    uses: NucleoidAI/actions/.github/workflows/deploy.yml@main
    secrets: inherit

  test:
    needs: deploy
    uses: NucleoidAI/actions/.github/workflows/test.yml@main
    secrets: inherit
